### ISSUE TITLE
npm build

### ISSUE THREAD

**Issue by mel-meng** [fileops/swmmReact_basic_example#1]
https://github.com/swmm-js/swmmReact_basic_example

should that be "npm run build", I got an error with that command.

**Comment by fileops** [comment]
You're right, thanks for helping me with that. It's almost time for an update to all of those examples. I'm really excited to compress the advanced UI and roll out the newer swmmNode package -should be compatible with most PySWMM techniques.Thanks again Mel.Issac GardnerswmmReact.org
